[package]
name = "inigo-rs"
version = "0.19.1"
edition = "2021"
description = "inigo middleware"
license = "MIT"
repository = "https://github.com/inigolabs/inigo-rs"
authors = ["Andrii <isoluchok@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apollo-router = { version = "1.2.1" }
async-trait = "0.1"
schemars = { version = "0.8", features = ["url"] }
serde = "1"
serde_json = "1"
tower = { version = "0.4", features = ["full"] }
http = "0.2.8"
router-bridge = "0.1.11"
libloading = "0.7"
lazy_static = "1.4.0"