name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Set ENV vars
        run: |
          TAG=$(git describe --tags --always `git rev-list --tags --max-count=1`)
          echo "IMAGE_TAG"=$TAG >> $GITHUB_ENV
          echo "IMAGE_NAME_ROUTER"=ghcr.io/inigolabs/inigo-rs/router >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and Push container image (router)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: |
            ${{ env.IMAGE_NAME_ROUTER }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME_ROUTER }}:latest
