name: Continuous Integration

on:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 20
          
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: test

