name: Continuous Integration

on:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 20
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Mold
        uses: rui314/setup-mold@v1
        
      - name: Setup Protoc
        uses: arduino/setup-protoc@v3

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargotarget-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test
